name: libasserest_ftp
description: FTP accessibility library in Asserest with security, username and password supported
version: '1.0.0-beta.1'
environment: 
  sdk: '>2.18.999 <4.0.0'
dependencies:
  async_task: ^1.0.20
  libasserest_interface: '>=1.0.0-beta.2 <2.0.0'
  meta: ^1.8.0
  ftpconnect: ^2.0.5
dev_dependencies:
  test: ^1.23.1
