name: libasserest_ftp
description: FTP accessibility library in Asserest with security, username and password supported
version: '1.0.0'
repository: https://github.com/Asserest/libasserest_ftp
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  async_task: ^1.0.2
  libasserest_interface: ^1.0.0
  ftpconnect: ^2.0.5
  quiver: ^3.2.1
  unique_list: ^1.0.1
  path: ^1.8.3
  random_string: ^2.3.1
dev_dependencies:
  test: ^1.24.2
